"""
F5 extra: build_multickpt_table.py

Scan lm_eval_step{N}/ directories and build a table comparing downstream metrics
across multiple checkpoints for each cell.  This tests whether S3pos maintains
its advantage at later (higher val_loss) checkpoints — the "regularization" hypothesis.

Output:
  results/stage3_v2/summary/multickpt_table.csv
  results/stage3_v2/summary/multickpt_table.md
"""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results" / "stage3_v2"
SUMMARY = RESULTS / "summary"
SUMMARY.mkdir(parents=True, exist_ok=True)

EXCLUDE_DIRS = {"summary", "figures"}
STEP_RE = re.compile(r"lm_eval_step(\d+)$")


def latest_results_json(d: Path) -> Optional[Path]:
    cands = list(d.rglob("results_*.json"))
    return max(cands, key=lambda p: p.stat().st_mtime) if cands else None


def extract_metrics(p: Path) -> dict:
    try:
        d = json.loads(p.read_text())
    except Exception:
        return {}
    out = {}
    R = d.get("results", {})
    if "gsm8k" in R:
        out["gsm8k_strict"] = R["gsm8k"].get("exact_match,strict-match")
        out["gsm8k_flex"] = R["gsm8k"].get("exact_match,flexible-extract")
    if "hellaswag" in R:
        out["hellaswag_acc_norm"] = R["hellaswag"].get("acc_norm,none")
    if "arc_challenge" in R:
        out["arc_challenge_acc_norm"] = R["arc_challenge"].get("acc_norm,none")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out_csv", type=Path, default=SUMMARY / "multickpt_table.csv")
    ap.add_argument("--out_md", type=Path, default=SUMMARY / "multickpt_table.md")
    args = ap.parse_args()

    rows = []
    for model_dir in sorted(RESULTS.iterdir()):
        if not model_dir.is_dir() or model_dir.name in EXCLUDE_DIRS:
            continue
        for dataset_dir in sorted(model_dir.iterdir()):
            if not dataset_dir.is_dir():
                continue
            for method_dir in sorted(dataset_dir.iterdir()):
                if not method_dir.is_dir():
                    continue
                for seed_dir in sorted(method_dir.iterdir()):
                    if not seed_dir.is_dir() or not seed_dir.name.startswith("seed"):
                        continue
                    seed = seed_dir.name.replace("seed", "")
                    for d in sorted(seed_dir.iterdir()):
                        m = STEP_RE.match(d.name)
                        if not m:
                            continue
                        step = int(m.group(1))
                        rj = latest_results_json(d)
                        if not rj:
                            continue
                        row = {
                            "model": model_dir.name,
                            "dataset": dataset_dir.name,
                            "method": method_dir.name,
                            "seed": seed,
                            "ckpt_step": step,
                        }
                        row.update(extract_metrics(rj))
                        rows.append(row)

    if not rows:
        print("no lm_eval_step*/ results found yet")
        return

    import csv
    cols = ["model", "dataset", "method", "seed", "ckpt_step",
            "gsm8k_strict", "gsm8k_flex", "hellaswag_acc_norm", "arc_challenge_acc_norm"]
    with args.out_csv.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow({k: (f"{v:.4f}" if isinstance(v, float) else v) for k, v in r.items()})
    print(f"wrote {args.out_csv} ({len(rows)} rows)")

    # Markdown: group by (model, dataset) then rows = (method, ckpt_step)
    by_md: dict[tuple, list] = {}
    for r in rows:
        by_md.setdefault((r["model"], r["dataset"]), []).append(r)

    lines = ["# Multi-checkpoint lm-eval table\n",
             "_Auto-generated by `scripts/build_multickpt_table.py`_\n"]
    order = ["lora_vanilla", "relora_baseline",
             "relora_diag_gated_S3pos", "relora_diag_gated_S3neg",
             "relora_random_drop", "relora_train_gated", "adalora", "dora"]
    for (model, dataset), grp in sorted(by_md.items()):
        lines.append(f"\n## {model} / {dataset}\n")
        lines.append("| method | ckpt_step | gsm8k_strict | gsm8k_flex | hellaswag | arc_chal |")
        lines.append("|---|---|---|---|---|---|")
        grp_sorted = sorted(grp, key=lambda r: (
            order.index(r["method"]) if r["method"] in order else 999, r["ckpt_step"]))
        for r in grp_sorted:
            def fmt(k):
                v = r.get(k)
                return f"{v*100:.2f}" if isinstance(v, float) else ""
            lines.append(f"| {r['method']} | {r['ckpt_step']} | {fmt('gsm8k_strict')} | {fmt('gsm8k_flex')} | {fmt('hellaswag_acc_norm')} | {fmt('arc_challenge_acc_norm')} |")

    args.out_md.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out_md}")


if __name__ == "__main__":
    main()
